--Multi sites CUST table
drop view [dbo].[ASVIEW_CAREG_UNPAID_INVOICEE01] 
go

CREATE view [dbo].[ASVIEW_CAREG_UNPAID_INVOICEE01] with SCHEMABINDING as  	select  		
a.INVID, a.UNITID, cast(a.RECNO as varchar) as RECNO,a.APPAREA,cast(a.ORDNO as varchar) as ORDNO,a.INVSUM,a.INVSUM0,a.BILLD,
cast(a.CUSTNO as varchar) as CUSTNO,b.LNAME,b.FNAME,a.DEPT, a.PAYSUM, a.DUED

from dbo.TEMPINV a, dbo.CUSTE01 b where a.PAYDATE is null  and a.RECACCNO is not null and a.CUSTNO=b.CUSTNO
and a.UNITID = 'E01'


GO
CREATE UNIQUE CLUSTERED INDEX [IDX_ASVIEW_CAREG_UNPAID_INVOICEE01] ON [dbo].[ASVIEW_CAREG_UNPAID_INVOICEE01] 
(
	[INVID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, 
DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
GO


CREATE FULLTEXT INDEX ON ASVIEW_CAREG_UNPAID_INVOICEE01(RECNO,ORDNO,CUSTNO,LNAME,FNAME) key index IDX_ASVIEW_CAREG_UNPAID_INVOICEE01 on FTCAT_AMDMS


grant select on ASVIEW_CAREG_UNPAID_INVOICEE01 to public

-- Single site CUST table
CREATE FULLTEXT CATALOG [FTCAT_AMDMS]WITH ACCENT_SENSITIVITY = OFF
AS DEFAULT
AUTHORIZATION [dbo]
GO

alter table TEMPINV add PAYDATE datetime, PAYSUM numeric(18,6)

drop view [dbo].[ASVIEW_CAREG_UNPAID_INVOICE] 
go

CREATE view [dbo].[ASVIEW_CAREG_UNPAID_INVOICE] with SCHEMABINDING as  	select  		
a.INVID, a.UNITID, cast(a.RECNO as varchar) as RECNO,a.APPAREA,cast(a.ORDNO as varchar) as ORDNO,a.INVSUM,a.INVSUM0,a.BILLD,
cast(a.CUSTNO as varchar) as CUSTNO,b.LNAME,b.FNAME,a.DEPT, a.PAYSUM,a.DUED

from dbo.TEMPINV a, dbo.CUST b where a.PAYDATE is null  and a.RECACCNO is not null and a.CUSTNO=b.CUSTNO



GO
CREATE UNIQUE CLUSTERED INDEX [IDX_ASVIEW_CAREG_UNPAID_INVOICE] ON [dbo].[ASVIEW_CAREG_UNPAID_INVOICE] 
(
	[INVID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, 
DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
GO



CREATE FULLTEXT INDEX ON ASVIEW_CAREG_UNPAID_INVOICE(RECNO,ORDNO,CUSTNO,LNAME,FNAME) key index IDX_ASVIEW_CAREG_UNPAID_INVOICE on FTCAT_AMDMS



drop view [dbo].[ASVIEW_CAREG_PAID_INVOICES01] 
go
CREATE view [dbo].[ASVIEW_CAREG_PAID_INVOICES01] with SCHEMABINDING
 as 
 	select  		
a._OID,CAST(a.RECEIPTNO as varchar) as RECEIPTNO, a.UNIT as UNITID, isnull(cast(a.INVOICENO as varchar),a.EXT_INVOICENO) as RECNO,a.MODULE,
isnull(cast(a.ORDERNO as varchar),a.EXT_ORDERNO) as ORDNO,a.AMOUNTTOPAY,a.TOTPAID,a.UPDATED_DATE as PAYDATE,
a.EXT_BILLD as BILLD,cast(a.CUSTNO as varchar) as CUSTNO,b.LNAME,b.FNAME, a.CASHBOXID, a.DEPARTMENT,a.LICNO,
isnull(a.CREDITNEWNO,0) as CREDITNEWNO,ISNULL(a.CREDITNOTE,0) as CREDITNOTE, ISNULL(a.CREDITOFNO,0) as CREDITOFNO
from dbo.CASHTRANSHS01 a , dbo.CUST b where a.CUSTNO = b.CUSTNO
go


CREATE UNIQUE CLUSTERED INDEX [IDX_ASVIEW_CAREG_PAID_INVOICES01] ON [dbo].[ASVIEW_CAREG_PAID_INVOICES01] 
(
	[_OID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, 
DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
GO



CREATE FULLTEXT INDEX ON ASVIEW_CAREG_PAID_INVOICES01(RECEIPTNO,RECNO,ORDNO,CUSTNO,LNAME,FNAME) key index IDX_ASVIEW_CAREG_PAID_INVOICES01 on FTCAT_AMDMS

grant select on ASVIEW_CAREG_PAID_INVOICES01 to public
grant select on ASVIEW_CAREG_UNPAID_INVOICE to public


--Create the Control data INVCAT_ADD manually if not exists, run this script for all sites
insert into CORWS01(CODAID,C1,C3,C4,C5) select 'INVCAT_ADD',SUBSTRING(codaid,1,1)+C1,CODAID,C1,C1 from CORWS01 where CODAID in ('klaskutyy','alaskutyy','vlaskutyy') and c5 like '%L%'
