drop table Z_FISCALPRINTER
CREATE TABLE [dbo].[Z_FISCALPRINTER](
	[RECEIPTNO] [int] NOT NULL,
	[TRANSFERRED] [datetime] NULL,
	[SITEID] [varchar](3) NOT NULL,
	 TYPE int not null,
	 STATUS int 
PRIMARY KEY CLUSTERED 
(
	[SITEID] ASC,
	[RECEIPTNO] ASC,
	TYPE
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

--ALTER TABLE Z_FISCALPRINTER
--add  TYPE int 

--ALTER TABLE Z_FISCALPRINTER
--add  STATUS int 
--GO

grant delete,update,insert,select on Z_FISCALPRINTER to public